version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@3.2

workflows:
  deploy-to-prod:
    jobs:
      - aws-ecr/build-and-push-image:
          name: 'build-and-push-image'
          context:
            - prod-aws-context
          account-url: AWS_ECR_ACCOUNT_URL
          create-repo: false
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./
          region: AWS_DEFAULT_REGION
          repo: ${AWS_ECR_REPO_NAME}
          skip-when-tags-exist: false
          tag: 'v0.1.<< pipeline.number >>'
          filters:
            branches:
              only:
                - master
            
      - aws-ecs/deploy-service-update:
          name: 'deploy-service-update'
          context:
            - prod-aws-context
          cluster: ${CLUSTER_NAME}
          container-image-name-updates: 'container=${CONTAINER_NAME},tag=v0.1.<< pipeline.number >>'
          family: ${FAMILY_NAME}
          service-name: ${SERVICE_NAME}
          force-new-deployment: true
          requires:
            - build-and-push-image
          filters:
            branches:
              only:
                - master