version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecr: circleci/aws-ecr@9.0.4
  aws-ecs: circleci/aws-ecs@4.0.0

workflows:
  deploy_to_dev:
    jobs:
      - aws-ecr/build_and_push_image:
          account_id: ${DEV_AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                role_arn: ${DEV_AWS_ROLE_ARN}
          context: dev-aws-context
          create_repo: false
          dockerfile: Dockerfile
          no_output_timeout: 20m
          path: .
          platform: linux/amd64
          profile_name: default
          public_registry: false
          push_image: true
          region: ${AWS_DEFAULT_REGION}
          repo: ${DEV_AWS_ECR_REPO_NAME}
          skip_when_tags_exist: false
          tag: "v0.1.<< pipeline.number >>"
          filters:
            branches:
              only:
                - dev
      - aws-ecs/deploy_service_update:
          auth:
            - aws-cli/setup:
                role_arn: ${DEV_AWS_ROLE_ARN}
          context: dev-aws-context
          profile_name: default
          cluster: ${DEV_CLUSTER_NAME}
          container_image_name_updates: 'container=${CONTAINER_NAME},tag=v0.1.<< pipeline.number >>'
          service_name: ${DEV_SERVICE_NAME}
          family: ${FAMILY_NAME}
          force_new_deployment: true
          requires:
            - aws-ecr/build_and_push_image
          filters:
            branches:
              only:
                - dev
  deploy_to_prod:
    jobs:
      - aws-ecr/build_and_push_image:
          account_id: ${PROD_AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                role_arn: ${PROD_AWS_ROLE_ARN}
          context:
            - prod-aws-context
          create_repo: false
          dockerfile: Dockerfile
          no_output_timeout: 20m
          path: .
          platform: linux/amd64
          profile_name: default
          public_registry: false
          push_image: true
          region: ${AWS_DEFAULT_REGION}
          repo: ${PROD_AWS_ECR_REPO_NAME}
          skip_when_tags_exist: false
          tag: ${CIRCLE_SHA1}
          filters:
            branches:
              only:
                - /^release\/.*/
      - aws-ecs/deploy_service_update:
          auth:
            - aws-cli/setup:
                role_arn: ${PROD_AWS_ROLE_ARN}
          context:
            - prod-aws-context
          cluster: ${PROD_CLUSTER_NAME}
          container_image_name_updates: 'container=${CONTAINER_NAME},tag=v0.1.<< pipeline.number >>'
          service_name: ${PROD_SERVICE_NAME}
          family: ${FAMILY_NAME}
          force_new_deployment: true
          requires:
            - aws-ecr/build_and_push_image
          filters:
            branches:
              only:
                - /^release\/.*/