version: 2.1

orbs:
  node: circleci/node@5.2.0
  aws-s3: circleci/aws-s3@3.1

jobs:
  build:
    docker:
      - image: cimg/node:21.4
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./

  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - attach_workspace:
          at: .
      - run: mkdir next
      - run: mkdir -p ./next/_next
      - run: mv ./.next/server/app/index.html ./next
      - run: mv ./.next/* ./next/_next
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: ./next
          to: s3://example
      - run:
          name: Invalidate CloudFront
          command: | 
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths /\*

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master