version: 2.1

orbs:
  node: circleci/node@5.2.0
  aws-cli: circleci/aws-cli@4.1.3
  aws-s3: circleci/aws-s3@4.0.0

jobs:
  build-for-dev:
    docker:
      - image: cimg/node:21.4
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build-dev
      - persist_to_workspace:
          root: .
          paths:
            - ./
  build-for-prod:
    docker:
      - image: cimg/node:21.4
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build-prod
      - persist_to_workspace:
          root: .
          paths:
            - ./
  deploy-to-dev:
    docker:
      - image: cimg/base:current
    steps:
      - aws-cli/setup:
          profile_name: default
          role_arn: ${DEV_AWS_ROLE_ARN}
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: ./dist
          to: s3://*
      - run:
          name: Invalidate CloudFront
          command: | 
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id ${DEV_DISTRIBUTION_ID} --paths /\*
  deploy-to-prod:
    docker:
      - image: cimg/base:current
    steps:
      - aws-cli/setup:
          profile_name: default
          role_arn: ${PROD_AWS_ROLE_ARN}
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: ./dist
          to: s3://*
      - run:
          name: Invalidate CloudFront
          command: | 
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id ${PROD_DISTRIBUTION_ID} --paths /\*

workflows:
  build-and-deploy-to-dev:
    jobs:
      - build-for-dev:
          filters:
            branches:
              only:
                - development
      - deploy-to-dev:
          context: dev-aws-context
          requires:
            - build-for-dev
          filters:
            branches:
              only:
                - development
  build-and-deploy-to-prod:
    jobs:
      - build-for-prod:
          filters:
            branches:
              only:
                - /^release\/.*/
      - deploy-to-prod:
          context: prod-aws-context
          requires:
            - build-for-prod
          filters:
            branches:
              only:
                - /^release\/.*/